### ISSUE TITLE
Hero doesn't show properly after using the menu nav.

### ISSUE THREAD

**Issue by lolpox** [adrianhajdin/portfolio#17]
![Untitled](https://github.com/adrianhajdin/portfolio/assets/33669515/21106a27-1718-4b48-b54d-f01d49a1e748)

It looks like this to me after clicking on the "Testimonials", when I scroll up the Hero spacing shrinks. Is this a known issue?

I'm reproducing this by following the instructions on the repo, not following the video course.

**Comment by mohdnas0001** [comment]
> ![Untitled](https://private-user-images.githubusercontent.com/33669515/340444344-21106a27-1718-4b48-b54d-f01d49a1e748.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1NTE1MjYsIm5iZiI6MTcxOTU1MTIyNiwicGF0aCI6Ii8zMzY2OTUxNS8zNDA0NDQzNDQtMjExMDZhMjctMTcxOC00YjQ4LWI1NGQtZjAxZDQ5YTFlNzQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDA1MDcwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0NDFlN2Y3NWEyODE0NzNkNDM4YTQ5MzEzZDI2YmVlZjU4NTY1MWExMjdmMmU1YmMwNmI4NmM3MTA4ZjYyMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gIIebogZz5cQ6tDP_N-Sc8wORZ17RyBpwbpU-eH7Foc)
> 
> It looks like this to me after clicking on the "Testimonials", when I scroll up the Hero spacing shrinks. Is this a known issue?
> 
> I'm reproducing this by following the instructions on the repo, not following the video course.

Has this been fixed ?

**Comment by lolpox** [comment]
@mohdnas0001 not yet!

**Comment by lolpox** [comment]
> Had the same issue. The solution was at app/page.tsx, at the main tag change the property overflow-hidden to overflow-clip. It should work.

It worked! Thanks 🙏

**Comment by mohdnas0001** [comment]
> > Had the same issue. The solution was at app/page.tsx, at the main tag change the property overflow-hidden to overflow-clip. It should work.
> 
> It worked! Thanks 🙏

Congrats 🤝
