### ISSUE TITLE
THREE.BufferGeometry.computeBoundingSphere(): Computed radius is NaN.

### ISSUE THREAD

**Issue by AkashJana18** [adrianhajdin/portfolio#33]
THREE.BufferGeometry.computeBoundingSphere(): Computed radius is NaN. The "position" attribute is likely to have NaN values. 
Even the deployed portfolio (on vercel) has this error.
I check the solution at pull request but it doesn't work.

**Comment by azozsol** [comment]
@AbdulDevHub 
Great job, thanks for fix it.
I had to adapt it to javaScript and it works very well.
