### ISSUE TITLE
Unhandled Runtime Error

### ISSUE THREAD

**Issue by Siddharth-Pandore** [adrianhajdin/portfolio#48]
I'm having issue of Unhandled Runtime Error, At 1:06 Portfolio timeline of Globe animation.
Does anyone have the solution?
![Unhandled Runtime Error](https://github.com/user-attachments/assets/e9671a21-38a8-4260-8d8d-483b873cc49b)

**Comment by ComissarLetlev** [comment]
did u find any solution for this??

**Comment by Siddharth-Pandore** [comment]
I haven't, Skipped the globe and moved forward ⏩

**Comment by ComissarLetlev** [comment]
just update react-three/fiber to alpha
https://www.npmjs.com/package/@react-three/fiber/v/9.0.0-alpha.8
i did and mine is working now

**Comment by Siddharth-Pandore** [comment]
Thanks Bro, It really worked!
Can you share how you troubleshoot?

**Comment by ComissarLetlev** [comment]
see the error closely, createRender react-three/fiber i figured something might be wrong so i just upgraded the version

**Comment by Siddharth-Pandore** [comment]
thanks bro
