### ISSUE TITLE
Bentogrid is not working 

### ISSUE THREAD

**Issue by Yashesh133** [adrianhajdin/portfolio#9]
when I upload a project on Vercel then bentoGrid is not set in the grid but Responsiveness is working good.
when I run the app it working well but it does not work in Vercel app.

check the code:- https://github.com/Yashesh133/modern-ui

vercel link :-  https://peronal-portfolio-modern-ui.vercel.app/

**Comment by Yashesh133** [comment]
when I upload a project on Vercel then bentoGrid is not set in the grid but Responsiveness is working good.
when I run the app it working well but it does not work in Vercel app.

check the code:- https://github.com/Yashesh133/modern-ui

vercel link :- https://peronal-portfolio-modern-ui.vercel.app/

**Comment by ArvinXO** [comment]
Make sure you are using optimised images, and take a look at your tailwind in your classNames, compare it to the source code, it could give you a hint. When in doubt, try chatgpt.

Good luck :)

**Comment by 1552537028** [comment]
hsu@jsmastery.pro      it is coppeid email from your web i think you followed jsmastrey goto Acenternityui copy the code and make changes in items

**Comment by 1552537028** [comment]
Goto Acenternityui copy the code and make changes in items not like jsmastrey

**Comment by Yashesh133** [comment]
it's not working. It gives the same result. if you have any other suggestions please give me.

**Comment by Yashesh133** [comment]
> Make sure you are using optimised images, and take a look at your tailwind in your classNames, compare it to the source code, it could give you a hint. When in doubt, try chatgpt.
> 
> Good luck :)
